const pages=["home","discounts","partners","car","history","profile"];
const names={home:"Главная",discounts:"Скидки",partners:"Партнёры",car:"Мой автомобиль",history:"История",profile:"Профиль"};
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));
function showPage(id){pages.forEach(p=>document.getElementById(p)?.classList.toggle("active",p===id));document.querySelectorAll("[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===id));document.getElementById("crumb").textContent=names[id]||"Главная";scrollTo({top:0,behavior:"smooth"});}
function openQR(discountId=null){document.getElementById("qrModal").classList.add("show");document.getElementById("qr").src="/static/placeholder.svg";let body={user_id:"APG-184729",discount:10};if(discountId)body.discount_id=discountId;fetch("/api/qr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).then(r=>r.blob()).then(blob=>document.getElementById("qr").src=URL.createObjectURL(blob)).catch(()=>{});}
function closeQR(){document.getElementById("qrModal").classList.remove("show")}
async function load(){const [d,p,h,s]=await Promise.all([fetch("/api/discounts").then(r=>r.json()),fetch("/api/partners").then(r=>r.json()),fetch("/api/history").then(r=>r.json()),fetch("/api/stats").then(r=>r.json())]);
document.getElementById("discountCount").textContent=d.length;document.getElementById("partnerMetric").textContent=s.partners+"+";
const card=x=>`<article class="deal"><div><div class="deal-top"><div class="deal-icon">%</div><span class="deal-off">-${x.discount}%</span></div><div style="margin-top:22px"><b>${x.partner}</b><small>${x.title}</small><small>⭐ ${x.rating} · ${x.distance}</small></div></div><button onclick="openQR(${x.id})">Получить скидку</button></article>`;
document.getElementById("homeDeals").innerHTML=d.slice(0,4).map(card).join("");document.getElementById("allDeals").innerHTML=d.map(card).join("");
renderPartners(p);renderHistory(h);}
function renderPartners(data){document.getElementById("partnersGrid").innerHTML=data.map(x=>`<article class="partner"><div class="partner-head"><div class="partner-logo">${x.name.split(" ").map(v=>v[0]).join("").slice(0,2)}</div><div><b>${x.name}</b><small>${x.category}</small></div><strong class="partner-off">-${x.discount}%</strong></div><div class="partner-meta"><span>⭐ ${x.rating}</span><span>⌖ ${x.distance}</span></div><button class="partner-button" onclick="openQR()">Получить скидку</button></article>`).join("");}
function renderHistory(data){const html=data.length?data.map(x=>`<div class="history-row"><div class="history-icon">${x.status==="USED"?"✓":"🎟"}</div><div><b>${x.partner}</b><small>${x.title} · ${new Date(x.created_at*1000).toLocaleString("ru-RU")}</small></div><strong>-${x.discount}%</strong></div>`).join(""):`<div class="history-row"><div><b>Пока нет операций</b><small>Активированные скидки появятся здесь.</small></div></div>`;document.getElementById("historyAll").innerHTML=html;document.getElementById("historyCar").innerHTML=html;}
document.getElementById("partnerSearch").addEventListener("input",filterPartners);document.getElementById("category").addEventListener("change",filterPartners);
async function filterPartners(){const q=document.getElementById("partnerSearch").value;const c=document.getElementById("category").value;const data=await fetch(`/api/partners?q=${encodeURIComponent(q)}&category=${encodeURIComponent(c)}`).then(r=>r.json());renderPartners(data);}
load();
