import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import QRCode from"qrcode";import{Home,TicketPercent,Gamepad2,Car,UserRound,Store,Settings,Plus,Trash2,Check,X,Trophy,QrCode,LogOut,MapPin,ShieldCheck}from"lucide-react";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";const token=()=>localStorage.getItem("apg_token");async function api(p,o={}){let h={"Content-Type":"application/json"};if(token())h.Authorization="Bearer "+token();let r=await fetch(API+p,{...o,headers:h}),j=await r.json();if(!r.ok)throw Error(j.detail||"Ошибка");return j}
function App(){let[me,setMe]=useState(null),[tab,setTab]=useState("home"),[offers,setOffers]=useState([]),[cars,setCars]=useState([]),[partners,setPartners]=useState([]),[queue,setQueue]=useState([]),[qr,setQr]=useState(null);useEffect(()=>{if(token())api("/api/me").then(setMe).catch(()=>localStorage.clear())},[]);useEffect(()=>{api("/api/discounts").then(setOffers);api("/api/partners").then(setPartners);if(token())api("/api/cars").then(setCars);if(me?.role==="OWNER")api("/api/owner/queue").then(setQueue)},[me,tab]);if(!me)return <Auth done={setMe}/>;let nav=[["home","Главная",Home],["discounts","Скидки",TicketPercent],["games","Игры",Gamepad2],["car","Моя машина",Car],["partners","Партнёры",Store],["profile","Профиль",UserRound]];if(me.role!=="CLIENT")nav.push(["manage","Управление",Settings]);return <div className="app"><header><b>APG</b><span>АВТО ПАРТНЕРСКАЯ ГРУППА</span><button onClick={()=>{localStorage.clear();location.reload()}}><LogOut/></button></header><main>{tab==="home"&&<HomePage me={me}offers={offers}go={setTab}/>} {tab==="discounts"&&<Discounts offers={offers}setQr={setQr}/>} {tab==="games"&&<Games/>}{tab==="car"&&<Cars cars={cars}reload={()=>api("/api/cars").then(setCars)}/>} {tab==="partners"&&<Partners data={partners}/>} {tab==="profile"&&<Profile me={me}/>} {tab==="manage"&&<Manage me={me}offers={offers}queue={queue}reload={()=>{api("/api/discounts").then(setOffers);api("/api/owner/queue").then(setQueue)}}/>}</main><nav>{nav.map(([id,t,I])=><button className={tab===id?"active":""}onClick={()=>setTab(id)}key={id}><I/><small>{t}</small></button>)}</nav>{qr&&<QR data={qr}close={()=>setQr(null)}/>}</div>}
function Auth({done}){let[reg,setReg]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState("");return <div className="auth"><strong>APG</strong><h1>{reg?"Создать аккаунт":"Войти в APG"}</h1>{reg&&<input placeholder="Имя"value={name}onChange={e=>setName(e.target.value)}/>}<input placeholder="Email"value={email}onChange={e=>setEmail(e.target.value)}/><input placeholder="Пароль"type="password"value={password}onChange={e=>setPassword(e.target.value)}/><button className="primary"onClick={async()=>{try{let j=await api(reg?"/api/auth/register":"/api/auth/login",{method:"POST",body:JSON.stringify(reg?{email,password,name}:{email,password})});localStorage.setItem("apg_token",j.token);done(j.user)}catch(e){alert(e.message)}}}>{reg?"Зарегистрироваться":"Войти"}</button><button className="link"onClick={()=>setReg(!reg)}>{reg?"Уже есть аккаунт":"Создать аккаунт"}</button><p>OWNER: owner@apg.local / owner123</p></div>}
function HomePage({me,offers,go}){return <><section className="hero"><div><span>APG PASS</span><h1>Твой автомобиль.<br/>Твои партнёры.<br/>Твои скидки.</h1><p>Один профиль для всей автомобильной экосистемы.</p></div><div className="pass"><span>APG PASS</span><b>{String(me.id).padStart(6,"0")}</b><small>{me.name}</small><QrCode/></div></section><div className="grid"><div className="stat"onClick={()=>go("discounts")}><TicketPercent/><span>Доступные скидки</span><b>{offers.length}</b></div><div className="stat"><Trophy/><span>APG POINTS</span><b>{me.points}</b></div></div><h2>Доступные предложения</h2><div className="cards">{offers.slice(0,3).map(o=><Offer o={o}key={o.id}setQr={()=>{}}/>)}</div></>}
function Discounts({offers,setQr}){return <><h1>Скидки</h1><div className="cards">{offers.length?offers.map(o=><Offer o={o}key={o.id}setQr={setQr}/>):<div className="empty">Пока нет одобренных предложений.</div>}</div></>}
function Offer({o,setQr}){return <article className="offer"><div className="offerimg">{o.image?<img src={o.image}/>:<TicketPercent/>}<b>-{o.percent}%</b></div><div><span>{o.address||"Партнёр APG"}</span><h2>{o.title}</h2><p>{o.description}</p><div className="row"><span><MapPin/>{o.address||"Адрес не указан"}</span><button className="primary"onClick={async()=>{try{setQr(await api("/api/discounts/"+o.id+"/qr",{method:"POST"}))}catch(e){alert(e.message)}}}>Получить QR</button></div></div></article>}
function QR({data,close}){let[src,setSrc]=useState("");useEffect(()=>{QRCode.toDataURL(data.token,{width:280}).then(setSrc)},[data]);return <div className="modal"><div className="dialog"><button className="close"onClick={close}>×</button><span>APG PASS</span><h2>QR для активации</h2>{src&&<img className="qr"src={src}/>}<code>{data.token}</code><p>Одноразовый QR, действует 15 минут.</p></div></div>}
function Games(){return <><h1>APG Games</h1><div className="games"><Race/><Parking/><Quiz/><Memory/></div></>}
function GameBox({title,children,score}){return <article className="game"><Trophy/><h2>{title}</h2><b className="score">{score}</b>{children}</article>}
function finish(game,score){return api("/api/games/result",{method:"POST",body:JSON.stringify({game,score})}).then(r=>alert(`+${r.xp} XP • +${r.points} POINTS`))}
function Race(){let[s,setS]=useState(0),[t,setT]=useState(15),[done,setD]=useState(false);useEffect(()=>{if(done)return;let x=setInterval(()=>setT(v=>{if(v<=1){setD(true);finish("APG Race",s);clearInterval(x);return 0}return v-1}),1000);return()=>clearInterval(x)},[done,s]);return <GameBox title="APG Race"score={s}><p>Время: {t}с</p><button onClick={()=>setS(v=>v+100)}>Обгон</button><button onClick={()=>setS(v=>v+60)}>Смена полосы</button></GameBox>}
function Parking(){let[s,setS]=useState(0),[n,setN]=useState(0);return <GameBox title="Perfect Parking"score={s}><p>Этап {n}/10</p><button onClick={()=>{let x=n+1;setN(x);setS(v=>v+100);if(x===10)finish("Perfect Parking",s+100)}}>Выставить угол</button></GameBox>}
function Quiz(){let q=[["Что измеряет тахометр?","обороты"],["Что делает ABS?","торможение"],["Что передаёт вращение к колёсам?","кардан"]], [i,setI]=useState(0),[s,setS]=useState(0);return <GameBox title="Auto Quiz"score={s}><p>{q[i]?.[0]||"Готово"}</p>{q[i]&&<button onClick={()=>{let a=prompt("Ответ");if(a?.toLowerCase().includes(q[i][1]))setS(v=>v+300);if(i===q.length-1)finish("Auto Quiz",s);else setI(i+1)}}>Ответить</button>}</GameBox>}
function Memory(){let[a,setA]=useState([]),vals=["🚗","🛞","🔧","⛽","🚗","🛞","🔧","⛽"];return <GameBox title="Auto Memory"score={a.length*100}><div className="memory">{vals.map((v,i)=><button key={i}disabled={a.includes(i)}onClick={()=>{let x=[...a,i];setA(x);if(x.length===8)finish("Auto Memory",800)}}>{a.includes(i)?v:"?"}</button>)}</div></GameBox>}
function Cars({cars,reload}){let[f,setF]=useState({brand:"",model:"",year:2026,vin:"",mileage:0});return <><h1>Моя машина</h1><div className="form">{Object.keys(f).map(k=><input key={k}placeholder={k}value={f[k]}onChange={e=>setF({...f,[k]:k==="year"||k==="mileage"?+e.target.value:e.target.value})}/>)}<button className="primary"onClick={async()=>{await api("/api/cars",{method:"POST",body:JSON.stringify(f)});reload()}}><Plus/>Добавить</button></div><div className="cards">{cars.map(c=><article className="panel"key={c.id}><Car/><h2>{c.brand} {c.model}</h2><p>{c.year} • {c.mileage} км • VIN {c.vin||"—"}</p><button className="danger"onClick={async()=>{await api("/api/cars/"+c.id,{method:"DELETE"});reload()}}><Trash2/>Удалить</button></article>)}</div></>}
function Partners({data}){return <><h1>Партнёры</h1><div className="cards">{data.length?data.map(p=><article className="panel"key={p.id}><Store/><h2>{p.company}</h2><p><MapPin/>{p.address}</p><p>{p.phone}</p><b>★ {p.rating}</b></article>):<div className="empty">Партнёров пока нет.</div>}</div></>}
function Profile({me}){return <><h1>Профиль</h1><div className="panel center"><div className="avatar">{me.name[0]}</div><h2>{me.name}</h2><p>{me.email}</p><span className="badge"><ShieldCheck/>{me.role}</span><div className="grid"><div className="stat"><Trophy/><span>POINTS</span><b>{me.points}</b></div><div className="stat"><Gamepad2/><span>XP</span><b>{me.xp}</b></div></div></div></>}
function Manage({me,offers,queue,reload}){let[f,setF]=useState({title:"",description:"",percent:10,address:"",contacts:"",image:""});return <><h1>Управление</h1><div className="panel"><span>{me.role}</span><h2>Добавить скидку</h2><input placeholder="Название"onChange={e=>setF({...f,title:e.target.value})}/><textarea placeholder="Описание"onChange={e=>setF({...f,description:e.target.value})}/><input type="number"placeholder="Процент"onChange={e=>setF({...f,percent:+e.target.value})}/><input placeholder="Адрес"onChange={e=>setF({...f,address:e.target.value})}/><input placeholder="Контакты"onChange={e=>setF({...f,contacts:e.target.value})}/><button className="primary"onClick={async()=>{await api("/api/discounts",{method:"POST",body:JSON.stringify(f)});reload()}}><Plus/>Создать</button></div>{me.role==="OWNER"&&<><h2>Модерация</h2>{queue.map(q=><div className="row panel"key={q.id}><b>{q.title}</b><button onClick={async()=>{await api("/api/owner/discount/"+q.id+"/approve",{method:"PATCH"});reload()}}><Check/></button><button onClick={async()=>{await api("/api/owner/discount/"+q.id+"/reject",{method:"PATCH"});reload()}}><X/></button></div>)}</>}<h2>Мои скидки</h2>{offers.map(o=><div className="row panel"key={o.id}><span>{o.title}</span><span>{o.status}</span><button onClick={async()=>{await api("/api/discounts/"+o.id,{method:"DELETE"});reload()}}><Trash2/></button></div>)}</>}
createRoot(document.getElementById("root")).render(<App/>);